import {
  createStyles,
  Image,
  Container,
  Title,
  Button,
  Group,
  Text,
  List,
  ThemeIcon,
} from '@mantine/core';

const useStyles = createStyles((theme) => ({
  inner: {
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: theme.spacing.xl * 2,
  },

  content: {
    maxWidth: 480,
    marginRight: theme.spacing.xl * 3,

    [theme.fn.smallerThan('md')]: {
      maxWidth: '100%',
      marginRight: 0,
    },
  },

  title: {
    color: theme.colorScheme === 'dark' ? theme.white : theme.black,
    fontFamily: `Greycliff CF, ${theme.fontFamily}`,
    fontSize: 32,
    lineHeight: 1.2,
    fontWeight: 900,

    [theme.fn.smallerThan('xs')]: {
      fontSize: 28,
    },
  },

  control: {
    'backgroundColor': '#f44336',
    '&:hover': {
      backgroundColor: '#9a2118',
    },
    [theme.fn.smallerThan('xs')]: {
      flex: 1,
    },
  },

  image: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',

    [theme.fn.smallerThan('md')]: {
      display: 'none',
    },
  },

  highlight: {
    position: 'relative',
    backgroundColor: theme.fn.variant({
      variant: 'light',
      color: theme.primaryColor,
    }).background,
    borderRadius: theme.radius.sm,
    padding: '4px 12px',
  },
}));

export const HeroBullets = () => {
  const { classes } = useStyles();
  return (
    <div>
      <Container>
        <div className={classes.inner}>
          <div className={classes.content}>
            <Title className={classes.title}>
              This page is a home for ChuckBuddy Bot. <br />
              Have fun and enjoy!
            </Title>
            <Text color='dimmed' mt='md'>
              There is no scientific evidence to suggest that jokes about Chuck
              Norris, or any other individual, are inherently "healthy" for
              people. However, jokes and humor, in general, have been shown to
              have potential benefits for mental health and well-being.
            </Text>

            <List
              mt={30}
              spacing='sm'
              size='sm'
              icon={
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  width='16'
                  height='16'
                  fill='black'
                  class='bi bi-chat-right-quote'
                  viewBox='0 0 16 16'
                >
                  <path d='M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z' />
                  <path d='M7.066 4.76A1.665 1.665 0 0 0 4 5.668a1.667 1.667 0 0 0 2.561 1.406c-.131.389-.375.804-.777 1.22a.417.417 0 1 0 .6.58c1.486-1.54 1.293-3.214.682-4.112zm4 0A1.665 1.665 0 0 0 8 5.668a1.667 1.667 0 0 0 2.561 1.406c-.131.389-.375.804-.777 1.22a.417.417 0 1 0 .6.58c1.486-1.54 1.293-3.214.682-4.112z' />
                </svg>
              }
            >
              <List.Item>
                Jokes about Chuck Norris are often exaggerated, absurd, and
                unexpected, which can make them particularly funny and
                entertaining. This type of humor can be a form of cognitive
                stimulation that challenges the brain to think creatively and
                can help improve mental flexibility.
              </List.Item>
              <List.Item>
                Humor can help reduce stress by triggering the release of
                endorphins, which are the body's natural feel-good chemicals.
                Laughing can also improve mood and provide a temporary escape
                from negative emotions or situations.
              </List.Item>
              <List.Item>
                Overall, while there is no specific health benefit to making or
                enjoying jokes about Chuck Norris, incorporating humor into
                one's daily life can be a positive way to cope with stress and
                improve overall well-being.
              </List.Item>
              <br />
              <b>
                Description is generated by{' '}
                <a href='https://chat.openai.com/'>ChatGPT</a>
              </b>
            </List>

            <Group mt={30}>
              <Button radius='xl' size='md' className={classes.control}>
                Get started
              </Button>
              <Button radius='xl' size='md' className={classes.control}>
                Source code
              </Button>
            </Group>
          </div>
          <Image
            src='https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/streams/2012/March/120305/143382-g-rnt-120305-norris-walker.jpg'
            className={classes.image}
            radius='md'
          />
        </div>
      </Container>
    </div>
  );
};
